apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-deployment
  labels:
    app: spotify
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spotify
  template:
    metadata:
      labels:
        app: spotify
    spec:
      containers:
      - name: spotify
        image: spotify:latest
        ports:
        - containerPort: 80
